<?php

namespace AppBundle\Repository;

/**
 * NifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NifRepository extends \Doctrine\ORM\EntityRepository
{
}
